apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasker-app-deployment
spec:
  selector:
    matchLabels:
      app: tasker-app
  replicas: 1
  template:
    metadata:
      labels:
        app: tasker-app
    spec:
      containers:
        - name: tasker-app
          image: local:tasker-app
          ports:
            - containerPort: 3000
