apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-harddrive
  labels:
    type: local
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: "/tmp/data"
